language: bash
services: docker

env:
  global:
    - BASE_IMAGE_NAME=alpine:latest
    - MY_IMAGE_NAME=manifest-test:latest

script:
  - |
    (
      # build image
      docker build -t manios/$MY_IMAGE_NAME --build-arg FROM_IMAGE_NAME=$BASE_IMAGE_NAME .
    )

after_script:
  - (docker images | egrep "manios/manifest-test +latest") || travis_terminate 1;
  - docker rmi "manios/$MY_IMAGE_NAME"