language: bash
services: docker

script:
  - |
    (
      # download qemu
      curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-arm-static.tar.gz | tar zxvf - -C .
      # prepare qemu
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      # build image
      docker build -t manios/manifest-test .
    )
