name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: image-info
    attributes:
      label: Image information
      description: |
        Can you please give us some information about the image you are using? In order to achive this, post here the output of the command:
        
        ```shell
        docker inspect --format='{{range $k,$v := .Config.Labels}}{{printf "* %s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v}}{{end}}{{"\n"}}{{end}}'  manios/nagios:[TAG]
        ```
    validations:
      required: true
  - type: dropdown
    id: image-architercture
    attributes:
      label: Image architecture
      description: |
        What is the architecture your docker image is using? You can easily find out by executing this 
        
        ```shell
        docker exec -it [container-name] /bin/sh -c 'apk --print-arch'
        ```
        in your running container.
      multiple: false
      options:
        - x86
        - amd64
        - arm/v6
        - arm/v7
        - arm64
    validations:
      required: true        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for markdown backticks. 
        
        For example, in order to view the last 200 log lines from the container you can run:

        ```shell
        docker logs --tail 200 [container-name]
        ```
      render: shell

