#!/bin/bash

set -exu

# Install the latest version of Docker EE
apt-get -y update
apt-get -y --only-upgrade install docker-ee
docker info

# https://github.com/docker/cli/issues/947
# https://docs.docker.com/engine/reference/commandline/dockerd/#description
# https://github.com/ckulka/docker-multi-arch-example/blob/master/multi-arch-manifest.yaml
# https://github.com/estesp/manifest-tool/issues/68
# https://github.com/ckulka/docker-multi-arch-example

echo "Is docker manifest enabled in CLI? " && \
(cat ~/.docker/config.json || true)

echo "Is docker manifest enabled in CLI? " && \
(cat /etc/docker/daemon.json || true)

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before

docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
