#!/bin/bash

set -exu

# Install the latest version of Docker EE
apt-get -y update
apt-get -y --only-upgrade install docker-ee
docker info

echo "Is docker manifest enabled? " && \
cat ~/.docker/config.json

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before

docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
