name: Nagios Build
# This workflow is triggered on pushes to the repository.
# Taken from tutorial
# https://github.com/gitschooldude/hello
# https://www.youtube.com/watch?v=-xIXFxuZCMI
# https://github.com/marketplace/actions/docker-setup-buildx
# https://github.com/marketplace/actions/docker-login
on: [push]

jobs:
  nagios-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # -
      #   name: Docker Buildx (build)
      #   run: |
      #     docker buildx build \
      #       --progress plain \
      #       --cache-from "type=local,src=/tmp/.buildx-cache" \
      #       --cache-to "type=local,dest=/tmp/.buildx-cache" \
      #       --platform linux/amd64 \
      #       --output "type=image,push=false" \
      #       --tag manifest-test:test-actions \
      #       --file ./Dockerfile ./
      # -
      #   name: Docker Buildx (push)
      #   run: |
      #     docker buildx build \
      #       --progress plain \          
      #       --cache-from "type=local,src=/tmp/.buildx-cache" \
      #       --platform linux/amd64 \
      #       --tag manifest-test:test-actions \
      #       --file ./Dockerfile ./ \
      #       --push         
      -
        name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: manifest-test
          tag: test-actions
          platform: linux/amd64 linux/arm/v6 linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect manifest-test:test-actions
